Repository neurobagel/ui, pull requests merged in 2024-10, with the labels that each got.

#112 [MNT] Removed build docker nightly workflow file
  .github/workflows/build_docker_nightly.yaml
Labels: pr-internal

#119 [CI] Implemented deploy workflow
  .github/workflows/deploy.yaml
  package-lock.json
  package.json
  src/components/CardContainer.tsx
  src/components/Download.tsx
  src/components/Instructions.tsx
  src/components/RepoCard.tsx
Labels: release, pr-internal

#137 [MNT] Fix badge link formatting in README.md
  README.md
Labels: skip-release
